### ISSUE TITLE
Will localhost continue to work?

### ISSUE THREAD

**Issue by ssbarnea** [best-doctor/pytest_network#11]
Will this plugin keep access to `localhost` or `127.0.0.1` working?

**Comment by Arondit** [comment]
@ssbarnea Hello and thank you for interest in our project. No, the plugin won't keep access to any IP. There is an issue for this idea, https://github.com/best-doctor/pytest_network/issues/6

I don't know, when we will be able to take it in work. If you decide to contribute with this idea, we would be very grateful and watch pull request fast.
