### ISSUE TITLE
Differences from pytest-socket?

### ISSUE THREAD

**Issue by miso-belica** [best-doctor/pytest_network#8]
Hi, I was searching for the possibility to disable internet access in my tests and found this package and https://github.com/miketheman/pytest-socket. I can see pytest-socket is older so maybe you just don't know about it.

And maybe you know it and this package has some advantages. Can you maybe describe in the README what is different? When to use this package and when pytest-socket?

If there is no clear difference, maybe you could work together with https://github.com/miketheman/pytest-socket on a single package, what do you think?

Thanks for the answers and maybe README update and have a nice day :)

**Comment by mcproger** [comment]
Hello! You are right, this plugin was heavily inspired by `pytest-socket`. However, when we started to update our django project to the 3 version, we ran into problems in the approach that pytest-socket uses to disable the network. We were not sure that we would wait for the update on time, so we decided to make our solution according to our needs.

So we will be glad if you use our solution, and we will also be very glad to have suggestions for improvement :)

**Comment by miso-belica** [comment]
So it means this project is specifically done for Django because https://github.com/miketheman/pytest-socket can't handle Django tests? Can you maybe add it to the README so it is clear for everyone? It would be a big help IMHO.

Unfortunately, I don't use Django and pytest-socket allows me to whitelist some hosts what is something I didn't see here in README. I was just not confident if I am not missing something here because there are 2 (in my eyes) identical projects.

**Comment by mcproger** [comment]
> this project is specifically done for Django

Not really. We ran into problems after running tests in asynchronous django and made this plugin. However, it should also work just fine with regular Python code. This can be seen in the [tests](https://github.com/best-doctor/pytest_network/blob/master/tests/test_network.py)

**Comment by mcproger** [comment]
@miso-belica Hello! Do you have any other questions? Or I can close this ticket?

**Comment by miso-belica** [comment]
No, I have no questions anymore. Thanks. How I understand it now is: the packages are pretty similar but if some problems with Django arise this one is preferred. Thank you
